### ISSUE TITLE
How can cparse be compiled by Visual Studio in Windows Environment

### ISSUE THREAD

**Issue by jojogh** [cparse/cparse#57]
How can cparse be compiled by Visual Studio in Windows Environment?

**Comment by VinGarcia** [comment]
Hello @jojogh,

We have had an issue earlier about this same issue #55. The user found a way to accomplish it by adding the 4 files of the `core-shunting-yard.o` library to his project, i.e.:

* shunting-yard.cpp
* packToken.cpp
* functions.cpp
* containers.cpp

He also tried compiling the builtin-features.o library but it did not work properly probably because of the static initialization used by this library. He overcame it by using the new build option of initializing this library manually:

```C++
#include "cparse/builtin-features.inc"

int main() {
  cparse_startup();
  
  // ... Your code goes here ...
}
```

> Note: I should already have added this to the docs, my mistake, I will add it right now.

This should do the trick. If it still does not work I could summon the previously mentioned user for help, he would probably be able to give you better tips than me since I am not used to working with Visual Studio.

I hope it helps.

**Comment by VinGarcia** [comment]
Hello @jojogh, I have added some documentation for this, but since this is not tested it might need some refining:

- [Download and Setup](https://github.com/cparse/cparse/wiki/Download-and-Setup#for-visual-studiowindows-users)

Tell me if there are any parts of it that are confusing.

**Comment by jojogh** [comment]
Many thanks, Vinícius Garcia ! I would take a look!

2018-05-10 22:50 GMT+08:00 Vinícius Garcia <notifications@github.com>:

**Comment by jojogh** [comment]
Hi, Vinicius,
I have successfully run the example following your instructions, here is
some things I want to share:
1. seems the project only support VS 2017, that should be C++ 11's problem;
2. If you build the code in Visual studio, you have to include the project
path;

I would test the project, many thanks!

Alex Zhang

2018-05-11 10:40 GMT+08:00 Yuanhao Zhang <yuanhao.zhang@gmail.com>:

**Comment by VinGarcia** [comment]
That's good @jojogh, I have updated the [Download and Setup page](https://github.com/cparse/cparse/wiki/Download-and-Setup) with your feedback. If you can please read it to see if I got it right =].

I hope it works well for you. Regards.

**Comment by jojogh** [comment]
Sure, no problem. I would take time to study and use this project, if I
meet any problem, I would seek help from you.

thanks

Alex Zhang

2018-05-14 10:49 GMT+08:00 Vinícius Garcia <notifications@github.com>:

**Comment by VinGarcia** [comment]
:+1: Then I am closing this issue.

Thanks @jojogh for the feedbacks and feel free to report any new problems.
