### ISSUE TITLE
operator precedence special case

### ISSUE THREAD

**Issue by grazba** [cparse/cparse#58]
Hi i did not know how to name the issue but here is an explanation : 
My goal is to be able to write this : 

`W("name1").L("name2")`

I have done this the way i wanted to with different classes, next i have to implement different operations possible between my classes. My issue is when using operators , when i write : 

`W("name1").L("name2") + W("name1").L("name3")`

it tries to add the data returned by the expression on the left to the function W (and i'm trying to make add up the two results) , of course when i put the brackets around the second expression it works fine, but i want to force the parser to evaluate the whole expression without putting the brackets.

thanks in advance !

**Comment by VinGarcia** [comment]
Hello @grazba, this is called operator precedence.

What you are saying you want is for the operator "." to have greater precedence than the operator "+" meaning it will be evaluated first, as in:

- `a*b + c*d`

Where the "+" operator will be evaluated last.

In CParse the operator precedence of each operator is defined using the `calculator::Default().opPrecedence` API, e.g.:

```C++
OppMap_t& opp = calculator::Default().opPrecedence;
// Note: The smaller the number the smaller the precedence:
opp.add("*", 1);
opp.add("+", 2);
```

So in your case it is likely that the number associated with "." is greater than the number associated with "+". You will need to move one of them up or down.

There is a short section in [Defining New Operations page][op-precedence] about this. Maybe it can help you further.

[op-precedence]: https://github.com/cparse/cparse/wiki/Defining-New-Operations#operators-precedence

In any case I hope this solves you problem, if not tell me.

**Comment by VinGarcia** [comment]
@grazba, one more thing. I have had another user wanting to use Visual Studio on his project. So I wrote some documentation based on your issue and his feedbacks in the [Download and Setup page](https://github.com/cparse/cparse/wiki/Download-and-Setup#for-visual-studiowindows-users). If you have some minutes could you read it and see if what I wrote makes sense?

I ask this because I don't have a VS environment to test that.

Thanks in advance =]

**Comment by grazba** [comment]
yeah that's exactly what i was suspecting  hence the name of the issue but i was not sure so yeah thanks i will try to fix it and close the issue when done.

For the the visual studio part , yes i will check the doc out and get back to you 👍 !

**Comment by VinGarcia** [comment]
Ops, I did not notice the name hehe, sorry. In any case, this looks like the kind of problem that would be fixed by changing the precedence values. I might be wrong since these expressions are complex but if this doesn't work tell me.

Also, there is a function I use to debug this type of expressions the `calculator::str()` function. You can use it like this:

```C++
calculator c1("W(\"name1\").L(\"name2\") + W(\"name1\").L(\"name3\")");
std::string rpn = c1.str();
std::cout << rpn << std::endl;
```

The result will show the operands and operators in Reverse Polish Notation. This notation shows exactly the order that the operations will take place, e.g.:

- `a b c + -`

Would be the same as:

- `a - (b + c)`

I.e. each operator operates on the previous 2 operands immediately before it.

This might help to understand how the expressions are being interpreted internally.

**Comment by grazba** [comment]
Thanks for the details it's pretty helpful for debugging indeed !

For the visual studio part, yes it is alright the only little detail is the note about c++ 11 support. The compiler always had issues with covering all of the standard , but since 2017 they are working hard on supporting c++ 11/14/17 and it should be 100% standard pretty soon, visual studio 2013 does support c++11 but doesn't support some features of the language in the case of CParse the only feature missing is reference qualifiers so i think the note should be check the compiler support of c++ features.

the precedence of operators did the trick everything is working smoothly, more features to add.

Thanks again !

**Comment by VinGarcia** [comment]
That's good @grazba and thanks for the feedback.

But give a little more details: this problem with the reference qualifiers causes the compilation to break or it works fine?

**Comment by grazba** [comment]
with VS2013 it won't compile , but deleting the "&&" after the function name (i forgot which one it was) will make it work just fine. The feature is available since VS2015 !

Here you can find details about standard support for visual studio maybe you can link it to the users : 
[support for c++ 11-14-17 with visual studio](https://msdn.microsoft.com/library/hh567368.aspx#corelanguagetable)
