### ISSUE TITLE
Overriding the = assignement operator for a class

### ISSUE THREAD

**Issue by grazba** [cparse/cparse#59]
Hi again,

Until now i had to define the different data types and function i was going to use and everything is working great. The data we handle can be pretty big so in our framework we never load anything in memory unless we are using it, so we use files/database which means reads and writes. The reading part is all done, data is transferred and handled by the parser. Now the writing part : i need to be able to write my own assignment operator to add some data handling specific to our codebase and of course to write the results on drive.

So first i thought it was an operator i had to write, but since the operator is expecting a specific signature, with const refs to the operands, i figured it's definitely not the route to go. I checked the keyword page on the wiki and i think that defining the = as a key character is the solution. But i'm not really sure how to go about it and i'm not really sure because i want to make a version specific to my types no to all possible assignments.

i hope you can put me on the correct way to go about it , thank you again for you help !

**Comment by VinGarcia** [comment]
Hello @grazba, this is an issue we still have on the system #52, I was postponing this because it is somewhat complex, but I will put my hands on it so it is fixed soon.

In the short term, we will have to think of an alternative solution.
One suggestion would be to implement it as a `update()` [type-specific function][type-specific-func], e.g.:

[type-specific-func]: https://github.com/cparse/cparse/wiki/Defining-New-Functions#type-specific-functions

- `myClass.update(MyObj)`

I am not entirely sure this solves it for you (at least temporarily), but inside the function you would have access to a "this" object that will be your "myClass" instance. e.g.:

```C++
packToken myClass_update(TokenMap scope) {
  MyClass& m = scope["this"].as<MyClass>();
  // ... do stuff ...
}
```

Also, if your class is based on the TokenMap type, you might prefer to put this function [in the prototype][prototype] of your class, since as a type-specific function it would affect all the tokens of type MAP, not only the ones which are instances of your class.

[prototype]: https://github.com/cparse/cparse/wiki/The-Power-of-the-TokenMap#tokenmaps-and-prototypes

----

If you are curious the problem with assignment operations is that it should receive not only the left/right operands as most operations do but also some kind of reference of the TokenMap where the left operand is stored. Otherwise changing the left token would not necessarily affect the original object, e.g.:

- `a.b = 10` requires the function to replace the value o the key "b" of the map "a".

I will take some time to think the best way to do this. And hopefully, this weekend, I will have time to fix it permanently.

**Comment by VinGarcia** [comment]
That's cool @grazba. I am happy to know you are really using this library =].

And about the issue I think I have fixed it =].

There are still some steps before I close issue #52:

- I need to write some tests
- I need to write some documentation
- I want to add 2 new built-in operations: ++ and --

However, if you pull the most recent version of the library and read the `builtin-features/operations.inc` file you'll see that the first operation defined is now the assignment operation. You may just copy it to your project and edit it as you would with any other operation. It should work fine.

**Comment by grazba** [comment]
Hi @VinGarcia  sorry for the late reply, i was pretty busy with some other projects :) !

I have one question about the assignment operator , what am i supposed to return ? and is the return value what makes the assignment ?

**Comment by VinGarcia** [comment]
This type of operator usually return the same thing that was assigned. The actual assignment is performed on the object which stores the variable being assigned, i.e. the `data->left->origin` object, which may be either a MAP or a LIST, in both cases you must use the index of the variable stored on `data->left->key`, which on the first case is a string and on the second case is an integer. The lines on the built-in operation that actually perform the assignment are:

- `map[var_name] = right;` - if it is inside a local object
- `data->scope[var_name] = right;` - if it is a new local variable (the scope is also of type MAP)
- `(*map)[var_name] = right;` - if it is an existing local variable

And for list containers:

- `list[index] = right;`

So as you can see this is a slightly more complicated operator, modifying it would probably be in the advanced features category, however, if you just want to implement a new behavior when the type in the left is an instance of your class you may just add an if (left->type == MY_TYPE) on the begining of the function, or alternatively add a new operation associated with the "=" operator and register it to be evaluated before the built-in one, e.g.:

```C++
opMap_t& opMap = calculator::Default().opMap;
opMap.add({MY_TYPE, "=", ANY_TYPE}, &MyAssign);
opMap.add({ANY_TYPE, "=", ANY_TYPE}, &Assign);
```

Should do the trick.

**Comment by grazba** [comment]
i can't get it work at all with my types , i tried writing my own function but even with standard one the assign function is not called and i get a " Unexpected operation with operator '=' and operands .." and the weird thing is that it writes the full maps (of my types) ignoring the str functions that i defined !

**Comment by grazba** [comment]
actually before this version i could assign my types to a variable and it did it by default , but now the assignment is just not working at all !

**Comment by VinGarcia** [comment]
Uhm, for some reason I can't see these messages on github, so I will answer
from my e-mail.

About this problem with the normal assignment not working that is may be
because the new version of the file `builtin-features/operations.inc` not
only defines the function Assign but also adds it to the operations map.
This was not required before but it is now:

```C++
    opMap_t& opMap = calculator::Default().opMap;
    opMap.add({ANY_TYPE, "=", ANY_TYPE}, &Assign);
```

This should fix the problem, if not try making a clean recompilation.

I have tested it on my own programming language, thus this is problably the
problem, however, if this doesn't fix it tell me and I will try to think of
other possibilities.

About the str functions I will test it here and try to figure out what is
going on, this is a feature I have only a few tests for, maybe it is not
working as expected or maybe I am not using it for reporting errors.



2018-05-23 12:28 GMT-03:00 grazba <notifications@github.com>:

**Comment by grazba** [comment]
i deleted the messages because it was my fault , i tried to get rid of the .inc files replaced them with regular .h ones and for some reason it did not work, so every built-feature was missing assignment and str but weirdly enough my types were still there. So yeah i deleted the messages because everything is working as expected (y) !

**Comment by VinGarcia** [comment]
@grazba, I just wanted you to know I have written a new section on the docs explaining how to create new operations of this type, I called it [Creating Advanced Operations](https://github.com/cparse/cparse/wiki/Defining-New-Operations#creating-advanced-operations).

I will probably read it again someday, I never trust the first version I write =P.

Also, you don't have to read it but if you do, it would be great to have your feedback.

Regards
