### ISSUE TITLE
Hexadecimal number computation

### ISSUE THREAD

**Issue by SweetVishnya** [cparse/cparse#79]
Hi!

What is the best way to perform hex numbers calculations? Like 0x123 + 0x456.

**Comment by VinGarcia** [comment]
Hello, @SweetVishnya I am sorry, I've only seen your message now.

I was going to tell you that the project doesn't support it, but it was a simple thing to add so I just did it:

5080c4990b49224fbe70313335c08d68cb5e238d

Now it should be easy to use hex numbers and also octal numbers, e.g.:

```C++
// Hex number:
calculator::calculate("0x1f").asInt()
// Octal number:
calculator::calculate("010").asInt() 
```

**Comment by VinGarcia** [comment]
I will close this issue, but feel free to reopen it if you find this solution doesn't solve your problem.

**Comment by SweetVishnya** [comment]
Hi!

I already implemented a shutting yard algorithm for my specific application. Also, your solution won't support uint64_t numbers.

**Comment by VinGarcia** [comment]
Hello @SweetVishnya, my fault for taking so long to answer sorry 😅 , but regarding uint64_t yeah I wont support it by default since the idea is to have a simple generic parser, but you should be able to personalize it creating:

[A new type](https://github.com/cparse/cparse/wiki/Defining-New-Types)

And then [a new reserved word such as `10u`](https://github.com/cparse/cparse/wiki/Defining-Reserved-Words) that would convert the previous token from an int into an unsigned int, or alternatively if you used it as a prefix `u10` then you could actually parse the number as an unsigned int from the start, which would be better.

Even though if you have already implemented it its probably better for you to just use your own implementation =P
